global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "node_api"
    static_configs:
      - targets: ["host.docker.internal:3050"]
    metrics_path: /api/metrics/

  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]